[build]
target = "riscv64gc-unknown-none-elf"


[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -m 2G -machine virt -nographic -serial mon:stdio -kernel"
rustflags = [
  "-C", "link-arg=-Tkernel.ld",
]